import { StyleSheet } from 'react-native';
import { colors, typography, spacing, borderRadius, MIN_TOUCH_TARGET } from '../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  // --- Top: Search + Filter ---
  topBar: {
    marginTop:50,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    gap: spacing.sm,
  },
  searchWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
    paddingHorizontal: spacing.md,
    minHeight: 44,
  },
  searchIcon: {
    fontSize: 18,
    marginRight: spacing.sm,
    color: colors.textMuted,
  },
  searchInput: {
    flex: 1,
    ...typography.bodySmall,
    color: colors.textPrimary,
    paddingVertical: spacing.sm,
  },
  filterButton: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterButtonIcon: {
    fontSize: 20,
    color: colors.textPrimary,
  },
  // --- New Entry card (dark) ---
  newEntryCard: {
    backgroundColor: colors.primary,
    marginHorizontal: spacing.md,
    marginBottom: spacing.lg,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    overflow: 'hidden',
  },
  newEntryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.lg,
  },
  newEntryTitle: {
    ...typography.h3,
    color: colors.white,
    marginBottom: spacing.xs,
  },
  newEntrySubtitle: {
    ...typography.bodySmall,
    color: colors.white,
    opacity: 0.9,
  },
  newEntryCloudIcon: {
    fontSize: 32,
    color: colors.white,
    opacity: 0.9,
  },
  newEntryActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  writeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.primary,
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  writeButtonText: {
    ...typography.button,
    color: colors.primary,
  },
  recordButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.white,
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  recordButtonText: {
    ...typography.button,
    color: colors.white,
  },
  recordIcon: {
    fontSize: 18,
    color: colors.white,
  },
  // --- Entry list ---
  list: {
    paddingHorizontal: spacing.md,
    paddingBottom: 100,
  },
  entryCard: {
    marginBottom: spacing.md,
    position: 'relative',
  },
  entryCardInner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  entryBadge: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  entryBadgeMic: {
    fontSize: 14,
  },
  entryBadgeLock: {
    fontSize: 14,
  },
  entryContent: {
    flex: 1,
    paddingRight: 36,
  },
  entryTitle: {
    ...typography.h3,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  entryPreview: {
    ...typography.bodySmall,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
  },
  entryLockedText: {
    color: colors.textMuted,
    letterSpacing: 1,
  },
  entryMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  entryDate: {
    ...typography.caption,
    color: colors.textMuted,
  },
  tags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  tag: {
    backgroundColor: colors.surface,
    paddingVertical: 2,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.sm,
  },
  tagText: {
    ...typography.caption,
    color: colors.textSecondary,
  },
  // --- Filter popup (small card next to filter icon) ---
  filterPopupOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10,
  },
  filterPopupCard: {
    position: 'absolute',
    top: 56,
    right: spacing.md,
    minWidth: 160,
    backgroundColor: colors.white,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.xs,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterPopupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
  },
  filterPopupRowSelected: {
    backgroundColor: colors.surface,
  },
  filterPopupClose: {
    position: 'absolute',
    top: spacing.xs,
    right: spacing.xs,
    padding: spacing.xs,
    zIndex: 1,
  },
  filterPopupCloseText: {
    fontSize: 18,
    color: colors.textMuted,
  },
  filterPopupOptionText: {
    ...typography.bodySmall,
    color: colors.textPrimary,
  },
  filterPopupOptionIcon: {
    fontSize: 14,
  },
  // --- Write bottom sheet ---
  writeOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  writeCard: {
    backgroundColor: colors.white,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    padding: spacing.xl,
    paddingBottom: spacing.section,
  },
  writeCardHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: spacing.md,
  },
  writeCloseBtn: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  writeCloseText: {
    fontSize: 22,
    color: colors.textMuted,
  },
  writeInputTitle: {
    ...typography.body,
    color: colors.textPrimary,
    backgroundColor: colors.background,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  writeInputBody: {
    ...typography.body,
    color: colors.textPrimary,
    backgroundColor: colors.background,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    minHeight: 120,
    textAlignVertical: 'top',
    marginBottom: spacing.md,
  },
  lockedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.lg,
    gap: spacing.sm,
  },
  lockedCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockedCheckboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  lockedLabel: {
    ...typography.bodySmall,
    color: colors.textPrimary,
  },
  lockedIcon: {
    fontSize: 16,
    marginLeft: spacing.xs,
  },
  saveEntryButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: MIN_TOUCH_TARGET,
  },
  saveEntryButtonText: {
    ...typography.button,
    color: colors.white,
  },
  // --- Mentora locked confirmation modal ---
  mentoraModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
  },
  mentoraModalCard: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.xl,
  },
  mentoraModalText: {
    ...typography.body,
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: spacing.xl,
    lineHeight: 24,
  },
  mentoraModalActions: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  mentoraCancelBtn: {
    flex: 1,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
  },
  mentoraCancelText: {
    ...typography.button,
    color: colors.textPrimary,
  },
  mentoraOkBtn: {
    flex: 1,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  mentoraOkText: {
    ...typography.button,
    color: colors.white,
  },
  listEmpty: {
    paddingVertical: spacing.xl,
    alignItems: 'center',
  },
  listEmptyText: {
    ...typography.bodySmall,
    color: colors.textMuted,
  },
});