import { StyleSheet, Dimensions } from 'react-native';
import { colors, typography, spacing, borderRadius } from '../theme';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scrollContent: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.section,
  },
  logoWrap: {
    alignItems: 'center',
    marginBottom: spacing.xxl,
  },
  logoIconWrap: {
    position: 'relative',
    marginBottom: spacing.md,
  },
  logoBrain: {
    fontSize: 56,
  },
  logoSparkle1: {
    position: 'absolute',
    top: -4,
    right: 8,
    fontSize: 18,
    color: '#D4A84B',
  },
  logoSparkle2: {
    position: 'absolute',
    top: 12,
    right: -8,
    fontSize: 14,
    color: '#D4A84B',
  },
  logoSparkle3: {
    position: 'absolute',
    bottom: 4,
    left: -12,
    fontSize: 12,
    color: '#D4A84B',
  },
  logoTitle: {
    ...typography.h1,
    color: colors.primary,
    marginBottom: spacing.xs,
  },
  logoSubtitle: {
    ...typography.bodySmall,
    color: colors.textMuted,
    textAlign: 'center',
    paddingHorizontal: spacing.lg,
  },
  fieldWrap: { marginBottom: spacing.lg },
  label: {
    ...typography.label,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    minHeight: 48,
  },
  inputIcon: { fontSize: 18, marginRight: spacing.sm, color: colors.textMuted },
  input: {
    flex: 1,
    ...typography.body,
    color: colors.textPrimary,
    paddingVertical: spacing.sm,
  },
  eyeBtn: { padding: spacing.xs },
  eyeIcon: { fontSize: 20 },
  forgotWrap: { alignSelf: 'flex-end', marginBottom: spacing.md },
  forgotText: { ...typography.bodySmall, color: colors.textMuted },
  rememberWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xl,
    gap: spacing.sm,
  },
  rememberText: { ...typography.bodySmall, color: colors.textPrimary },
  signInBtn: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    marginBottom: spacing.xl,
  },
  signInBtnText: { ...typography.button, color: colors.white },
  orWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xl,
    gap: spacing.md,
  },
  orLine: { flex: 1, height: 1, backgroundColor: colors.borderLight },
  orText: { ...typography.caption, color: colors.textMuted },
  socialWrap: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing.lg,
    marginBottom: spacing.xxl,
  },
  socialBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  socialIcon: { fontSize: 20, color: colors.info, fontWeight: '600' },
  socialIconG: { fontSize: 20, color: colors.textPrimary, fontWeight: '700' },
  footerWrap: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerText: { ...typography.bodySmall, color: colors.textMuted },
  footerLink: { ...typography.bodySmall, color: colors.info, fontWeight: '600' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
  },
  modalCard: {
    width: '100%',
    maxWidth: width * 0.85,
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.xl,
  },
  modalTitle: {
    ...typography.h3,
    color: colors.textPrimary,
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  modalBody: {
    ...typography.body,
    color: colors.textSecondary,
    marginBottom: spacing.xl,
    textAlign: 'center',
    lineHeight: 24,
  },
  modalBtn: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    alignItems: 'center',
  },
  modalBtnText: { ...typography.button, color: colors.white },
});
